sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t theautonater801/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true theautonater801/react-test npm test

after_success:
  - docker build -t theautonater801/multi-client ./client
  - docker build -t theautonater801/multi-nginx ./nginx
  - docker build -t theautonater801/multi-server ./server
  - docker build -t theautonater801/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push theautonater801/multi-client
  - docker push theautonater801/multi-nginx
  - docker push theautonater801/multi-server
  - docker push theautonater801/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "multi-docker"
  end: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-590183884677"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"